name: final_work
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI / design
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.8

  # State & local storage
  flutter_riverpod: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Pour générer des UUID
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
