name: social_balans
description: Een app om je digitale balans te verbeteren.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # État et gestion des données
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Supabase
  supabase_flutter: ^2.5.0
  postgres: ^3.5.6
  uuid: ^4.4.0
  flutter_dotenv: ^5.1.0

  # UI et animations
  cupertino_icons: ^1.0.8
  graphic: ^2.1.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  shimmer: ^3.0.0

  # Utilitaires
  intl: ^0.19.0
  path_provider: ^2.1.3
  path: ^1.9.0
  device_info_plus: ^11.4.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.0
  share_plus: ^11.0.0
  permission_handler: ^11.3.1
  app_usage: ^4.0.1
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  web: ^1.0.0
  collection: ^1.18.0

  jwt_decoder: ^2.0.1
  crypto: ^3.0.3
  image_picker: ^1.1.2

  # Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.0.0
  cloud_firestore: ^5.0.2

  # Device apps
  # device_apps: ^2.2.0  # Package discontinued - causing build issues

  # Usage stats
  usage_stats: ^1.0.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1
  custom_lint: ^0.7.0
  riverpod_lint: ^2.3.8

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/
    - assets/animations/
    - assets/icons/

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true
  ios: true
